### ISSUE TITLE
Server Crash : com.mindoo.domino.jna.errors.NotesError: Error converting date/time value from GMT to local zone

### ISSUE THREAD

**Issue by eknori** [klehmann/domino-jna#18]
IBM Domino (r) Server (64 Bit) (Release 9.0.1FP7HF370  for Linux/64) 13.01.2018 09:41:48
Linux serv02.fritz.box 3.10.0-693.1.1.el7.x86_64 #1 SMP Thu Aug 3 08:15:31 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

DirectoryScanner crashes on RHEL while scanning databases on a remote server.

`com.mindoo.domino.jna.errors.NotesError: Error searching database
        at com.mindoo.domino.jna.NotesSearch.search(NotesSearch.java:559)
        at com.mindoo.domino.jna.NotesSearch.searchFiles(NotesSearch.java:237)
        at com.mindoo.domino.jna.NotesDatabase.searchFiles(NotesDatabase.java:2086)
        at com.mindoo.domino.jna.directory.DirectoryScanner.scan(DirectoryScanner.java:67)
        at com.mindoo.domino.jna.directory.DirectoryScanner.scan(DirectoryScanner.java:52)
        at de.eknori.dots.manager.ScannerManager$1.call(ScannerManager.java:104)
        at de.eknori.dots.BaseJNA$1.call(BaseJNA.java:55)
        at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:481)
        at de.eknori.dots.BaseJNA.runWithSession(BaseJNA.java:51)
        at de.eknori.dots.manager.ScannerManager.run(ScannerManager.java:66)
        at de.eknori.dots.tools.Commands._apptool(Commands.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
        at java.lang.reflect.Method.invoke(Method.java:611)
        at com.ibm.dots.internal.OSGIConsoleAdaptor.runCommand(OSGIConsoleAdaptor.java:288)
        at com.ibm.dots.task.ServerTaskManager._processCommand(ServerTaskManager.java:669)
        at com.ibm.dots.task.ServerTaskManager.processCommand(ServerTaskManager.java:630)
Caused by: com.mindoo.domino.jna.errors.NotesError: Error converting date/time value from GMT to local zone: [5767168, 83886086]
        at com.mindoo.domino.jna.utils.NotesDateTimeUtils.innardsToCalendar(NotesDateTimeUtils.java:287)
        at com.mindoo.domino.jna.utils.NotesDateTimeUtils.timeDateToCalendar(NotesDateTimeUtils.java:57)
        at com.mindoo.domino.jna.internal.ItemDecoder.decodeTimeDate(ItemDecoder.java:87)
        at com.mindoo.domino.jna.internal.NotesLookupResultBufferDecoder$ItemValueTableData.getItemValue(NotesLookupResultBufferDecoder.java:525)
        at com.mindoo.domino.jna.internal.NotesLookupResultBufferDecoder$ItemTableData.asMap(NotesLookupResultBufferDecoder.java:1002)
        at com.mindoo.domino.jna.directory.DirectoryScanner$1.noteFound(DirectoryScanner.java:75)
        at com.mindoo.domino.jna.NotesSearch$1.invoke(NotesSearch.java:440)
        at com.mindoo.domino.jna.internal.NotesNativeAPI64.NSFSearchExtended3(Native Method)
        at com.mindoo.domino.jna.NotesSearch$2.run(NotesSearch.java:538)
        at com.mindoo.domino.jna.NotesSearch$2.run(NotesSearch.java:534)
        at java.security.AccessController.doPrivileged(AccessController.java:413)
        at com.mindoo.domino.jna.NotesSearch.search(NotesSearch.java:534)`

**Comment by eknori** [comment]
[jna--1833998801.zip](https://github.com/klehmann/domino-jna/files/1628245/jna--1833998801.zip)

**Comment by klehmann** [comment]
Do you mean "code stops with an exception" or "crashes the whole server"?

**Comment by eknori** [comment]
Crashes the whole server.

Von meinem iPad gesendet

Am 13.01.2018 um 14:07 schrieb Karsten Lehmann <notifications@github.com>:

Do you mean "code stops with an exception" or "crashes the whole server"?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


Ulrich Krause
Am Zaunbusch 8
40822 Mettmann

Fon: +49 (0) 2104 9525671
Fax: +49 (0) 2104 9528506
Mobile: +49 (0) 151 20009036

Blog: http://www.eknori.de
Twitter: eknori
<a href="http://www.eknori.de">

</a>

**Comment by eknori** [comment]
from domino-jna-stack
```

java.lang.Exception
	at com.mindoo.domino.jna.internal.NotesNativeAPI$MethodInterceptorWithStacktraceLogging.intercept(NotesNativeAPI.java:405)
	at com.mindoo.domino.jna.internal.NotesNativeAPI64$$EnhancerByCGLIB$$37b0f807.FTGetLastIndexTime(<generated>)
	at com.mindoo.domino.jna.NotesDatabase.getFTLastIndexTime(NotesDatabase.java:1864)
	at com.mindoo.domino.jna.NotesDatabase.isFTIndex(NotesDatabase.java:1830)
	at de.eknori.dots.manager.ScannerManager$2.call(ScannerManager.java:425)
	at de.eknori.dots.BaseJNA$1.call(BaseJNA.java:56)
	at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:451)
	at de.eknori.dots.BaseJNA.runWithSession(BaseJNA.java:52)
	at de.eknori.dots.manager.ScannerManager.addFromApiDatabase(ScannerManager.java:411)
	at de.eknori.dots.manager.ScannerManager.processData(ScannerManager.java:174)
	at de.eknori.dots.manager.ScannerManager.access$600(ScannerManager.java:53)
	at de.eknori.dots.manager.ScannerManager$1.call(ScannerManager.java:115)
	at de.eknori.dots.BaseJNA$1.call(BaseJNA.java:56)
	at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:481)
	at de.eknori.dots.BaseJNA.runWithSession(BaseJNA.java:52)
	at de.eknori.dots.manager.ScannerManager.run(ScannerManager.java:66)
	at de.eknori.dots.tools.Commands._apptool(Commands.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at com.ibm.dots.internal.OSGIConsoleAdaptor.runCommand(OSGIConsoleAdaptor.java:288)
	at com.ibm.dots.task.ServerTaskManager._processCommand(ServerTaskManager.java:669)
	at com.ibm.dots.task.ServerTaskManager.processCommand(ServerTaskManager.java:630)
```

**Comment by klehmann** [comment]
Weird. I don't see anything in the code that could produce a crash in com.mindoo.domino.jna.NotesDatabase.getFTLastIndexTime(). I guess this does not happen all the time? Always for the same database?
You can use https://github.com/klehmann/domino-jna/blob/master/domino-jna/src/main/java/com/mindoo/domino/jna/utils/DumpUtil.java#L33 to write a log file for each scanned database, if the crash happens before Domino can write a console message.

Another thing to try is to disable direct mapping by setting the JNA mode via the system property "dominojna.jnamode" to "classic" (instead of the default "direct"), e.g. in your plugin's activator class.

See this method for details how this works:
https://github.com/klehmann/domino-jna/blob/master/domino-jna/src/main/java/com/mindoo/domino/jna/internal/NotesNativeAPI.java#L74

**Comment by eknori** [comment]
getting this error again; not crashing the server, but directoryScanner.scan() not working

```
com.mindoo.domino.jna.errors.NotesError: Error searching database
	at com.mindoo.domino.jna.NotesSearch.search(NotesSearch.java:557)
	at com.mindoo.domino.jna.NotesSearch.searchFiles(NotesSearch.java:235)
	at com.mindoo.domino.jna.NotesDatabase.searchFiles(NotesDatabase.java:2087)
	at com.mindoo.domino.jna.directory.DirectoryScanner.scan(DirectoryScanner.java:67)
	at com.mindoo.domino.jna.directory.DirectoryScanner.scan(DirectoryScanner.java:52)
	at de.eknori.dots.manager.ScannerManager$1.call(ScannerManager.java:106)
	at de.eknori.dots.BaseJNA$1.call(BaseJNA.java:63)
	at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:481)
	at de.eknori.dots.BaseJNA.runWithSession(BaseJNA.java:59)
	at de.eknori.dots.manager.ScannerManager.run(ScannerManager.java:72)
	at de.eknori.dots.tools.Commands._apptool(Commands.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.ibm.dots.internal.OSGIConsoleAdaptor.runCommand(OSGIConsoleAdaptor.java:288)
	at com.ibm.dots.task.ServerTaskManager._processCommand(ServerTaskManager.java:669)
	at com.ibm.dots.task.ServerTaskManager.processCommand(ServerTaskManager.java:630)
Caused by: com.mindoo.domino.jna.errors.NotesError: Error converting date/time value from GMT to local zone: [5767168, 83886086]
	at com.mindoo.domino.jna.utils.NotesDateTimeUtils.innardsToCalendar(NotesDateTimeUtils.java:287)
	at com.mindoo.domino.jna.utils.NotesDateTimeUtils.timeDateToCalendar(NotesDateTimeUtils.java:57)
	at com.mindoo.domino.jna.internal.ItemDecoder.decodeTimeDate(ItemDecoder.java:87)
	at com.mindoo.domino.jna.internal.NotesLookupResultBufferDecoder$ItemValueTableData.getItemValue(NotesLookupResultBufferDecoder.java:528)
	at com.mindoo.domino.jna.internal.NotesLookupResultBufferDecoder$ItemTableData.asMap(NotesLookupResultBufferDecoder.java:1005)
	at com.mindoo.domino.jna.directory.DirectoryScanner$1.noteFound(DirectoryScanner.java:75)
	at com.mindoo.domino.jna.NotesSearch$1.invoke(NotesSearch.java:438)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:415)
	at com.sun.jna.Function.invoke(Function.java:354)
	at com.sun.jna.Library$Handler.invoke(Library.java:244)
	at com.sun.proxy.$Proxy46.NSFSearchExtended3(Unknown Source)
	at com.mindoo.domino.jna.NotesSearch$2.run(NotesSearch.java:536)
	at com.mindoo.domino.jna.NotesSearch$2.run(NotesSearch.java:532)
	at java.security.AccessController.doPrivileged(AccessController.java:677)
	at com.mindoo.domino.jna.NotesSearch.search(NotesSearch.java:532)
	... 17 more
```

**Comment by klehmann** [comment]
The innards [5767168, 83886086] seem to be invalid. At least TimeGMToLocalZone returns true, which means (according to the C API documentation):

(routine)  -  Returns FALSE if successful and TRUE if not.

Can you debug which summary buffer item produces the error? I guess for other databases, this item can be decoded? What does the Domino Administrator UI display for this value?

I can catch this error in the DirectoryScanner and go on scanning, but I am curious why this conversion does not work.
The crash you had was probably not related to this error, but to the bug fixed by dc35613cf9adc5ed091f8a26f300e741c8cd6268 which could crash on any Java garbage collection or to another issue (e.g. active JNA protected mode which is instable for multiththreaded apps, hopefully fixed by edbaa367ef510fb83b7f97b19996e23312409019).

**Comment by klehmann** [comment]
I created a test document with a datetime item of the innards. Looks like these values really are not valid:

<img width="374" alt="bildschirmfoto 2018-01-24 um 08 52 34" src="https://user-images.githubusercontent.com/4291861/35320410-00c3b3fa-00e4-11e8-9c82-351829d2f780.png">

**Comment by klehmann** [comment]
Ok, it's a bit more complicated. The Notes.jar does return a Vector with one DateTime, that returns an empty String for toString() and throws an error 4458 (invalid date specification)when calling DateTime.toJavaDate().
Since Domino JNA returns Calendar instead of NotesTimeDate, I could not do the same (I think there are no "invalid" Calendar values).

With 8c7ee7acffe8e64d8b6ff068bfdc67b910759850 we will now return null when calling NotesDateTimeUtils.innardsToCalendar(boolean useDayLight, int gmtOffset, int[] innards).

When such an invalid value is found in a NotesNote, we return a Calendar with day=1, month=1, year=1, hour=0, minute=0, second=0, millis=0.
This should not really happen in reality though.

Please check if your code is now working.
