### ISSUE TITLE
HTMLAPI Problem converting to HTML (error code: 14941, raw error with all flags: 14941)

### ISSUE THREAD

**Issue by kenizhou** [klehmann/domino-jna#24]
Dear klehmann,

trouble you again. we encounter following error when convert an email with a gif image.  the gif image which must be an animation image. [(e.g. sample gif](https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjQ4ufOxojgAhVM_GEKHcqKCGAQjRx6BAgBEAU&url=https%3A%2F%2Fgiphy.com%2Fgifs%2Fanimation-art-illustration-l1J9sqWg6hZnMKrBK&psig=AOvVaw1PXPA374hqq-STBEK6S7tU&ust=1548492601698194) )

I think it should be IBM API's bug.

> com.mindoo.domino.jna.errors.NotesError: HTMLAPI Problem converting to HTML (error code: 14941, raw error with all flags: 14941)
	at com.mindoo.domino.jna.errors.NotesErrorUtils.toNotesError(NotesErrorUtils.java:53)
	at com.mindoo.domino.jna.errors.NotesErrorUtils.checkResult(NotesErrorUtils.java:26)
	at com.mindoo.domino.jna.NotesNote.convertHtmlElement(NotesNote.java:4089)
	at com.mindoo.domino.jna.NotesNote.convertHtmlElement(NotesNote.java:4032)
	at com.mindoo.domino.jna.NotesNote$HtmlConversionResult$1.writeImage(NotesNote.java:4231)

**Comment by klehmann** [comment]
Can you send me an example image that is causing the problem?

**Comment by kenizhou** [comment]
then compose an email like this:

![image](https://user-images.githubusercontent.com/614477/51740597-6b2de600-20cf-11e9-8626-ea37dc37b600.png)

**Comment by kenizhou** [comment]
@klehmann can you reproduce the problem? thanks!

**Comment by klehmann** [comment]
Sorry, I cannot reproduce the error. Trying locally against the Notes 10.0.1 Mac client here.
What are you using? Code running on a 9.0.1 FP10 server?

Here is my source code:
```java
package com.mindoo.domino.jna.test;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.util.EnumSet;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;

import org.junit.Test;

import com.mindoo.domino.jna.NotesDatabase;
import com.mindoo.domino.jna.NotesNote;
import com.mindoo.domino.jna.NotesNote.HtmlConvertOption;
import com.mindoo.domino.jna.html.IHtmlConversionResult;
import com.mindoo.domino.jna.html.IHtmlImageRef;
import com.mindoo.domino.jna.html.ReferenceType;
import com.mindoo.domino.jna.html.TargetType;

import lotus.domino.Session;

/**
 * Tests case for HTML conversion of richtext
 * 
 * @author Karsten Lehmann
 */
public class TestHtmlAPI extends BaseJNATestClass {

	@Test
	public void testRichtextHtmlConversion() {
		runWithSession(new IDominoCallable<Object>() {

			@Override
			public Object call(Session session) throws Exception {
				// NotesDatabase db = new NotesDatabase(session, "Server1/Mindoo", "mail/klehmann.nsf");
				NotesDatabase db = new NotesDatabase(session, "", "mail/klehmann.nsf");
				NotesNote note = db.openNoteByUnid("4E805D7E942F9E82C125839000743483");
				
				EnumSet<ReferenceType> refTypeFilter = null;
				Map<ReferenceType,EnumSet<TargetType>> targetTypeFilter = null;
				
				IHtmlConversionResult convResult = note.convertItemToHtml("Body", EnumSet.allOf(HtmlConvertOption.class),
						refTypeFilter, targetTypeFilter);
				String html = convResult.getText();
				System.out.println("HTML:\n"+html);

				List<IHtmlImageRef> images = convResult.getImages();
				
				File htmlOutDir = new File("/tmp");
				htmlOutDir.mkdirs();
				
				final AtomicInteger imgIdx = new AtomicInteger();

				for (IHtmlImageRef currImage : images) {
					String currRefTxt = currImage.getReferenceText();
					System.out.println("Image ref text: "+currRefTxt);
					
					File imgFile = new File(htmlOutDir, "img"+imgIdx+"."+currImage.getFormat());
					currImage.writeImage(imgFile);
					html = html.replace(currRefTxt, imgFile.getName());
					imgIdx.incrementAndGet();
				}
				
				File htmlFile = new File(htmlOutDir, "index.html");
				if (htmlFile.exists())
					htmlFile.delete();
				
				FileOutputStream fOut = new FileOutputStream(htmlFile);
				OutputStreamWriter outWriter = new OutputStreamWriter(fOut, "UTF-8");
				outWriter.write("<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" /></head>");
				outWriter.write("<body>");
				outWriter.write(html);
				outWriter.write("</body></html>");
				outWriter.close();
				
				return null;
			}
		});
	}
	
}
```

Output:
```html
[001F6A:000002-00000700003B7700] 28/01/2019 22:18:44,82 CSRF Init: iNotes_WA_Security_ReturnUrlCheck> c_CSRFReturnUrlCheck: 1

[001F6A:000002-00000700003B7700] 28/01/2019 22:18:44   No browser configuration file found, using defaults
[001F6A:000002-00000700003B7700] iNotes Init: Credential Store Configuration not enabled, less secure mode.
HTML:
<img src="/mail%5Cklehmann.nsf/0/4e805d7e942f9e82c125839000743483/Body/0.84?OpenElement&FieldElemFormat=gif" width="480" height="347">111
Image ref text: /mail%5Cklehmann.nsf/0/4e805d7e942f9e82c125839000743483/Body/0.84?OpenElement&FieldElemFormat=gif
```

**Comment by kenizhou** [comment]
yes, I am using notes 9.0.1 FP 10 on Windows.  then I attach a nsf for you later.

**Comment by sattam-datum** [comment]
What is the resolution for this issue, as i encountered same issue for some embedded images

**Comment by klehmann** [comment]
I don't know. Can you attach a sample DB to reproduce the issue? Maybe there are some options as a workaround. I also added some more conversion options in the last week.

**Comment by sattam-datum** [comment]
I cannot reproduce the issue on new documents, and the DB size is huge , 
but if you can provide me with latest snapshot with new code needed, so i can test?
