### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Unable to load library 'notes': Native library (darwin/libnotes.dylib)

### ISSUE THREAD

**Issue by fortezhuo** [klehmann/domino-jna#42]
Hi, Thanks for great repo. I have cloned this repo and run the standalone app. And found problem like this 

```
mvn -DJVMPARAMS=-d64 -DDOMINOOSGIDIR=/Applications/HCL\ Notes.app/Contents/MacOS -DDOMINODIR=/Applications/HCL\ Notes.app/Contents/MacOS -Djava.library.path=/Application/HCL\ Notes.app/Contents/MacOS  -DNOTESINI=~/Library/Preferences/Notes\ Preferences exec:java -Dexec.mainClass=com.mindoo.domino.jna.samples.standaloneapp.DominoJNAStandaloneSampleApp

Initializing Domino JNA with mode Classic
com.mindoo.domino.jna.errors.NotesError: Error initializing Domino JNA API
	at com.mindoo.domino.jna.internal.NotesNativeAPI.get(NotesNativeAPI.java:254)
	at com.mindoo.domino.jna.utils.NotesInitUtils.notesInitExtended(NotesInitUtils.java:44)
	at com.mindoo.domino.jna.samples.standaloneapp.DominoJNAStandaloneSampleApp.main(DominoJNAStandaloneSampleApp.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'notes': Native library (darwin/libnotes.dylib) not found in resource path ([file:/Users/forte/Workspace/standalone-app-sample/target/classes/, file:/Users/forte/.m2/repository/com/mindoo/domino/domino-jna/0.9.24/domino-jna-0.9.24.jar, file:/Users/forte/.m2/repository/org/elasticsearch/jna/4.5.1/jna-4.5.1.jar, file:/Users/forte/.m2/repository/com/drewnoakes/metadata-extractor/2.11.0/metadata-extractor-2.11.0.jar, file:/Users/forte/.m2/repository/com/adobe/xmp/xmpcore/5.1.3/xmpcore-5.1.3.jar, file:/Users/forte/.m2/repository/cglib/cglib/3.2.6/cglib-3.2.6.jar, file:/Users/forte/.m2/repository/org/ow2/asm/asm/6.0/asm-6.0.jar, file:/Users/forte/.m2/repository/org/apache/ant/ant/1.9.6/ant-1.9.6.jar, file:/Users/forte/.m2/repository/org/apache/ant/ant-launcher/1.9.6/ant-launcher-1.9.6.jar, file:/Users/forte/.m2/repository/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.4.2/concurrentlinkedhashmap-lru-1.4.2.jar, file:/Users/forte/.m2/repository/com/sun/mail/javax.mail/1.5.2/javax.mail-1.5.2.jar, file:/Users/forte/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar])
```

**Comment by klehmann** [comment]
I haven't tried starting the program with Maven. It's important to have the Notes program directory (/Applications/HCL Notes.app/Contents/MacOS) in the PATH so that the libnotes.dylib / .so / .dll can be found. That seems to be missing in your environment.

**Comment by fortezhuo** [comment]
I have create bash script for launch

```
#!/bin/sh
export NOTES_HOME=/Applications/HCL\ Notes.app/Contents/MacOS
export DYLD_LIBRARY_PATH=$NOTES_HOME
export LD_LIBRARY_PATH=$NOTES_HOME
export CLASSPATH=.:$NOTES_HOME/jvm/lib/ext/Notes.jar:$CLASSPATH
export Notes_ExecDirectory=$NOTES_HOME
export NOTESBIN=$NOTES_HOME
export PATH=$PATH:$NOTES_HOME
export NotesINI=~/Library/Preferences/Notes Preferences

mvn exec:java
```
But still no luck. And I still investigate this problem, and will update again..

**Comment by klehmann** [comment]
I modified the standalone sample application. Please check if it now runs on your machine.
https://github.com/klehmann/domino-jna/tree/master/standalone-app-sample

**Comment by fortezhuo** [comment]
Thanks for your repo. Now it run perfectly. And I wanna ask if this repo is production ready ? And where can I find the documentation API about this repo ?

**Comment by klehmann** [comment]
We are using it in many production apps on a daily basis, so we are probably the first ones who find out if something is broken. 
If you need any commercial agreement about payed support / assistance, feel free to contact us (https://www.mindoo.com) and I am sure we can work something out.

Regarding documentation, there are some blog articles in the further information section (https://github.com/klehmann/domino-jna#further-information) that might help.

There's no getting started documentation yet. It's of course on the todo list, as are better test cases and adding more APIs like MIME handling.

**Comment by fortezhuo** [comment]
OK. Thank you for your explanation. I think I can close this issue
